version: '3.9'
networks:
  net:
services:
  mongo:
    image: mongo:6.0.2
    restart: always
    networks:
      - net
    ports:
      - "27017:27117"
    volumes:
      - /home/nifont/mongo/data:/data/db
    env_file:
      - .mongoenv

  server:
    build: medals/.
    restart: always
    depends_on:
      - mongo
    networks:
      - net
    ports:
      - "8080:8180"
    volumes:
      - /home/nifont/medals/files:/app/files
    env_file:
      - .env
    container_name: medals-server
    image: medals/server:1
  web:
    build: bravo/.
    restart: always
    depends_on:
      - server
    networks:
      - net
    ports:
      - "3000:3000"
    env_file:
      - .webenv
    container_name: medals-web
    image: medals/web:1