version: '3.9'
networks:
  net:
services:
  server:
    build: server/.
    restart: always
    networks:
      - net
    ports:
      - "8080:8080"
    volumes:
      - files:/app/files
    env_file:
      - .env
    container_name: medals-server
    image: medals/server:1